# Generated by Django 4.2.2 on 2024-11-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SportEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.IntegerField(blank=True, null=True)),
                ("type", models.CharField(blank=True, null=True)),
                ("sport", models.CharField(blank=True, null=True)),
                ("discip", models.CharField(blank=True, null=True)),
                ("program", models.CharField(blank=True, null=True)),
                ("gender_age", models.CharField(blank=True, null=True)),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
                ("country", models.CharField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, null=True)),
                ("city", models.CharField(blank=True, null=True)),
                ("participants", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "sport_events",
                "managed": False,
            },
        ),
    ]
